/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Product1Import } from './routes/product1'
import { Route as LoginImport } from './routes/login'
import { Route as ExamplesImport } from './routes/examples'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const Product1Route = Product1Import.update({
  id: '/product1',
  path: '/product1',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ExamplesRoute = ExamplesImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/product1': {
      id: '/product1'
      path: '/product1'
      fullPath: '/product1'
      preLoaderRoute: typeof Product1Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRoute
  '/login': typeof LoginRoute
  '/product1': typeof Product1Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRoute
  '/login': typeof LoginRoute
  '/product1': typeof Product1Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRoute
  '/login': typeof LoginRoute
  '/product1': typeof Product1Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/examples' | '/login' | '/product1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/examples' | '/login' | '/product1'
  id: '__root__' | '/' | '/examples' | '/login' | '/product1'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesRoute: typeof ExamplesRoute
  LoginRoute: typeof LoginRoute
  Product1Route: typeof Product1Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesRoute: ExamplesRoute,
  LoginRoute: LoginRoute,
  Product1Route: Product1Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/examples",
        "/login",
        "/product1"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/examples": {
      "filePath": "examples.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/product1": {
      "filePath": "product1.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
