/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegistrationImport } from './routes/registration'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as CatalogIndexImport } from './routes/catalog/index'
import { Route as AccountIndexImport } from './routes/account/index'
import { Route as Test1Import } from './routes/test/1'
import { Route as ProductsIdImport } from './routes/products/$id'
import { Route as AccountManageAddressesImport } from './routes/account/manage-addresses'
import { Route as AccountEditImport } from './routes/account/edit'
import { Route as AccountChangePasswordImport } from './routes/account/change-password'
import { Route as CatalogCategorySplatImport } from './routes/catalog/$category.$'

// Create/Update Routes

const RegistrationRoute = RegistrationImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CatalogIndexRoute = CatalogIndexImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRoute,
} as any)

const AccountIndexRoute = AccountIndexImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRoute,
} as any)

const Test1Route = Test1Import.update({
  id: '/test/1',
  path: '/test/1',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIdRoute = ProductsIdImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRoute,
} as any)

const AccountManageAddressesRoute = AccountManageAddressesImport.update({
  id: '/account/manage-addresses',
  path: '/account/manage-addresses',
  getParentRoute: () => rootRoute,
} as any)

const AccountEditRoute = AccountEditImport.update({
  id: '/account/edit',
  path: '/account/edit',
  getParentRoute: () => rootRoute,
} as any)

const AccountChangePasswordRoute = AccountChangePasswordImport.update({
  id: '/account/change-password',
  path: '/account/change-password',
  getParentRoute: () => rootRoute,
} as any)

const CatalogCategorySplatRoute = CatalogCategorySplatImport.update({
  id: '/catalog/$category/$',
  path: '/catalog/$category/$',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationImport
      parentRoute: typeof rootRoute
    }
    '/account/change-password': {
      id: '/account/change-password'
      path: '/account/change-password'
      fullPath: '/account/change-password'
      preLoaderRoute: typeof AccountChangePasswordImport
      parentRoute: typeof rootRoute
    }
    '/account/edit': {
      id: '/account/edit'
      path: '/account/edit'
      fullPath: '/account/edit'
      preLoaderRoute: typeof AccountEditImport
      parentRoute: typeof rootRoute
    }
    '/account/manage-addresses': {
      id: '/account/manage-addresses'
      path: '/account/manage-addresses'
      fullPath: '/account/manage-addresses'
      preLoaderRoute: typeof AccountManageAddressesImport
      parentRoute: typeof rootRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdImport
      parentRoute: typeof rootRoute
    }
    '/test/1': {
      id: '/test/1'
      path: '/test/1'
      fullPath: '/test/1'
      preLoaderRoute: typeof Test1Import
      parentRoute: typeof rootRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexImport
      parentRoute: typeof rootRoute
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogIndexImport
      parentRoute: typeof rootRoute
    }
    '/catalog/$category/$': {
      id: '/catalog/$category/$'
      path: '/catalog/$category/$'
      fullPath: '/catalog/$category/$'
      preLoaderRoute: typeof CatalogCategorySplatImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/registration': typeof RegistrationRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/account/edit': typeof AccountEditRoute
  '/account/manage-addresses': typeof AccountManageAddressesRoute
  '/products/$id': typeof ProductsIdRoute
  '/test/1': typeof Test1Route
  '/account': typeof AccountIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/catalog/$category/$': typeof CatalogCategorySplatRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/registration': typeof RegistrationRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/account/edit': typeof AccountEditRoute
  '/account/manage-addresses': typeof AccountManageAddressesRoute
  '/products/$id': typeof ProductsIdRoute
  '/test/1': typeof Test1Route
  '/account': typeof AccountIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/catalog/$category/$': typeof CatalogCategorySplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/registration': typeof RegistrationRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/account/edit': typeof AccountEditRoute
  '/account/manage-addresses': typeof AccountManageAddressesRoute
  '/products/$id': typeof ProductsIdRoute
  '/test/1': typeof Test1Route
  '/account/': typeof AccountIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/catalog/$category/$': typeof CatalogCategorySplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/registration'
    | '/account/change-password'
    | '/account/edit'
    | '/account/manage-addresses'
    | '/products/$id'
    | '/test/1'
    | '/account'
    | '/catalog'
    | '/catalog/$category/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/registration'
    | '/account/change-password'
    | '/account/edit'
    | '/account/manage-addresses'
    | '/products/$id'
    | '/test/1'
    | '/account'
    | '/catalog'
    | '/catalog/$category/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/registration'
    | '/account/change-password'
    | '/account/edit'
    | '/account/manage-addresses'
    | '/products/$id'
    | '/test/1'
    | '/account/'
    | '/catalog/'
    | '/catalog/$category/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RegistrationRoute: typeof RegistrationRoute
  AccountChangePasswordRoute: typeof AccountChangePasswordRoute
  AccountEditRoute: typeof AccountEditRoute
  AccountManageAddressesRoute: typeof AccountManageAddressesRoute
  ProductsIdRoute: typeof ProductsIdRoute
  Test1Route: typeof Test1Route
  AccountIndexRoute: typeof AccountIndexRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  CatalogCategorySplatRoute: typeof CatalogCategorySplatRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RegistrationRoute: RegistrationRoute,
  AccountChangePasswordRoute: AccountChangePasswordRoute,
  AccountEditRoute: AccountEditRoute,
  AccountManageAddressesRoute: AccountManageAddressesRoute,
  ProductsIdRoute: ProductsIdRoute,
  Test1Route: Test1Route,
  AccountIndexRoute: AccountIndexRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  CatalogCategorySplatRoute: CatalogCategorySplatRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/login",
        "/register",
        "/registration",
        "/account/change-password",
        "/account/edit",
        "/account/manage-addresses",
        "/products/$id",
        "/test/1",
        "/account/",
        "/catalog/",
        "/catalog/$category/$"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/registration": {
      "filePath": "registration.tsx"
    },
    "/account/change-password": {
      "filePath": "account/change-password.tsx"
    },
    "/account/edit": {
      "filePath": "account/edit.tsx"
    },
    "/account/manage-addresses": {
      "filePath": "account/manage-addresses.tsx"
    },
    "/products/$id": {
      "filePath": "products/$id.tsx"
    },
    "/test/1": {
      "filePath": "test/1.tsx"
    },
    "/account/": {
      "filePath": "account/index.tsx"
    },
    "/catalog/": {
      "filePath": "catalog/index.tsx"
    },
    "/catalog/$category/$": {
      "filePath": "catalog/$category.$.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
